spring:
  application:
    name: catmall-gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: member_route
          uri: lb://catmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
            #  http://localhost:88/api/member/memberlevel/list
            #  http://localhost:9000/member/memberlevel/list

        - id: ware_route
          uri: lb://catmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
            #  http://localhost:88/api/ware/wareinfo/list
            #  http://localhost:12000/ware/wareinfo/list

        - id: product_route
          uri: lb://catmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
            #  http://localhost:88/api/product/category/list/tree
            #  http://localhost:11000/product/category/list/tree

        - id: third_party_route
          uri: lb://catmall-third-party
          predicates:
            - Path=/api/third-party/**
          filters:
            - RewritePath=/api/third-party/(?<segment>.*),/$\{segment}
            #  http://localhost:88/api/third-party/oss/policy
            #  http://localhost:13000/oss/policy

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
            #  http://localhost:88/api/app/login
            #  http://localhost:8080/renren-fast/app/login

        - id: coupon_route
          uri: lb://catmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: order_route
          uri: lb://catmall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: catmall_host_route
          uri: lb://catmall-product
          predicates:
            - Host=catmall.com,item.catmall.com

        - id: catmall_search_route
          uri: lb://catmall-search
          predicates:
            - Host=search.catmall.com

        - id: catmall_auth_route
          uri: lb://catmall-auth-server
          predicates:
            - Host=auth.catmall.com

        - id: catmall_cart_route
          uri: lb://catmall-cart
          predicates:
            - Host=cart.catmall.com

        - id: catmall_order_route
          uri: lb://catmall-order
          predicates:
            - Host=order.catmall.com

        - id: catmall_member_route
          uri: lb://catmall-member
          predicates:
            - Host=member.catmall.com

        - id: catmall_seckill_route
          uri: lb://catmall-seckill
          predicates:
            - Host=seckill.catmall.com


server:
  port: 88

